### ISSUE TITLE
Update Elastic Search submodule

### ISSUE THREAD

**Issue by tomjn** [Chassis/Chassis_Elasticsearch#17]
Right now it's using an out of date commit with various deprecation warnings regarding validation functions, which don't exist in the latest commit

**Comment by BronsonQuick** [comment]
From memory I don't think this will be an easy upgrade as I think when I tested this last time some of the parameters we use aren't backwards compatible.

**Comment by pdewouters** [comment]
For reference, I attempted `vagrant box update` on an existing install and it won't provision the updated box.

```==> default: Running provisioner: shell...
    default: Running: inline script
    default: Warning: ModuleLoader: module 'elasticsearch' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules\n   (file & line not available)
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["/vagrant/extensions/chassis_elasticsearch/modules/elasticsearch/manifests/init.pp", 427]:
    default:    (location: /vagrant/puppet/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Array. There is further documentation for validate_legacy function in the README. at ["/vagrant/extensions/chassis_elasticsearch/modules/elasticsearch/manifests/init.pp", 438]:
    default:    (location: /vagrant/puppet/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Integer. There is further documentation for validate_legacy function in the README. at ["/vagrant/extensions/chassis_elasticsearch/modules/elasticsearch/manifests/init.pp", 439]:
    default:    (location: /vagrant/puppet/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
    default: Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at ["/vagrant/extensions/chassis_elasticsearch/modules/elasticsearch/manifests/init.pp", 440]:
    default:    (location: /vagrant/puppet/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
    default: Warning: This method is deprecated, please use match expressions with Stdlib::Compat::Array instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/vagrant/extensions/chassis_elasticsearch/modules/elasticsearch/manifests/init.pp", 454]:
    default:    (location: /vagrant/puppet/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
    default: Error: Evaluation Error: Error while evaluating a Function Call, unsupported release bionic (file: /vagrant/extensions/chassis_elasticsearch/modules/java/manifests/params.pp, line: 143, column: 20) on node siemens.local
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by BronsonQuick** [comment]
@pdewouters You'll need to update the submodules in the elasticsearch extension because it contains a newer java submodule. Once you've done that the extension will successfully provision but the warnings for the deprecated functions will still be there.

**Comment by mikeselander** [comment]
@BronsonQuick is there a good way of making those warnings fo away? They add quite a bit of noise to the provisioning process and leave a user unsure if something's gone wrong or now.

**Comment by BronsonQuick** [comment]
@mikeselander I had a look into it a while ago and they didn't make the Elasticsearch submodule backwards compatible which would mean we'd have to add some parsing in the configuration logic we use here so I didn't worry about it. I might have a look into it this afternoon for you.
